default: &default
  adapter: postgresql
  encoding: unicode
  username: cody
  password:
  pool: 5

development:
  <<: *default
  database: goodsamaritan_development

test:
  <<: *default
  database: goodsamaritan_test

production:
  <<: *default
  database: goodsamaritan_production
